### ISSUE TITLE
Using ES 6.4 exceptions

### ISSUE THREAD

**Issue by ghost** [sofastack/sofa-lookout#73]
由于现有环境一直是ES6.4供各服务使用，所以我用sofa lookout-server 1.6.0-release也用es6.4。
但是两个索引，lookout-search-metrics初始化了，lookout-active-metrics没有初始化。异常日志如下：

2019-10-11 17:24:4910.200.5.33419abfffCaused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'selfMetricsStarter': Unsatisfied dependency expressed through field 'exportChainManager'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'exportManager' defined in class path resource [com/alipay/sofa/lookout/gateway/metrics/starter/MetricPipelineConfiguration.class]: Unsatisfied dependency expressed through method 'exportManager' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'esMetricsExportChain' defined in class path resource [com/alipay/sofa/lookout/gateway/metrics/exporter/es/spring/bean/config/EsExporterConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alipay.sofa.lookout.gateway.core.prototype.exporter.chain.ExportChain]: Factory method 'esMetricsExportChain' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'esMetricsExporter' defined in class path resource [com/alipay/sofa/lookout/gateway/metrics/exporter/es/spring/bean/config/EsExporterConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alipay.sofa.lookout.gateway.metrics.exporter.es.ESMetricExporter]: Factory method 'esMetricsExporter' threw exception; nested exception is java.lang.IllegalStateException: java.lang.IllegalStateException: this alias is conflicted with an index name:lookout-active-metrics
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:596)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1411)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:849)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:67)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
2019-10-11 17:24:4910.200.5.33419abfff	at com.alipay.sofa.lookout.boot.GatewayBootstrap.main(GatewayBootstrap.java:45)
2019-10-11 17:24:4910.200.5.33419abfff	... 20 more
2019-10-11 17:24:4910.200.5.33419abfffCaused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'exportManager' defined in class path resource [com/alipay/sofa/lookout/gateway/metrics/starter/MetricPipelineConfiguration.class]: Unsatisfied dependency expressed through method 'exportManager' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'esMetricsExportChain' defined in class path resource [com/alipay/sofa/lookout/gateway/metrics/exporter/es/spring/bean/config/EsExporterConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alipay.sofa.lookout.gateway.core.prototype.exporter.chain.ExportChain]: Factory method 'esMetricsExportChain' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'esMetricsExporter' defined in class path resource [com/alipay/sofa/lookout/gateway/metrics/exporter/es/spring/bean/config/EsExporterConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alipay.sofa.lookout.gateway.metrics.exporter.es.ESMetricExporter]: Factory method 'esMetricsExporter' threw exception; nested exception is java.lang.IllegalStateException: java.lang.IllegalStateException: this alias is conflicted with an index name:lookout-active-metrics
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:509)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1321)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1160)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1247)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
2019-10-11 17:24:4910.200.5.33419abfff	... 37 more
2019-10-11 17:24:4910.200.5.33419abfffCaused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'esMetricsExportChain' defined in class path resource [com/alipay/sofa/lookout/gateway/metrics/exporter/es/spring/bean/config/EsExporterConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alipay.sofa.lookout.gateway.core.prototype.exporter.chain.ExportChain]: Factory method 'esMetricsExportChain' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'esMetricsExporter' defined in class path resource [com/alipay/sofa/lookout/gateway/metrics/exporter/es/spring/bean/config/EsExporterConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alipay.sofa.lookout.gateway.metrics.exporter.es.ESMetricExporter]: Factory method 'esMetricsExporter' threw exception; nested exception is java.lang.IllegalStateException: java.lang.IllegalStateException: this alias is conflicted with an index name:lookout-active-metrics
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:627)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:456)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1321)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1160)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1463)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1427)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveMultipleBeans(DefaultListableBeanFactory.java:1318)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1205)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
2019-10-11 17:24:4910.200.5.33419abfff	... 50 more
2019-10-11 17:24:4910.200.5.33419abfffCaused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alipay.sofa.lookout.gateway.core.prototype.exporter.chain.ExportChain]: Factory method 'esMetricsExportChain' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'esMetricsExporter' defined in class path resource [com/alipay/sofa/lookout/gateway/metrics/exporter/es/spring/bean/config/EsExporterConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alipay.sofa.lookout.gateway.metrics.exporter.es.ESMetricExporter]: Factory method 'esMetricsExporter' threw exception; nested exception is java.lang.IllegalStateException: java.lang.IllegalStateException: this alias is conflicted with an index name:lookout-active-metrics
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622)
2019-10-11 17:24:4910.200.5.33419abfff	... 67 more
2019-10-11 17:24:4910.200.5.33419abfffCaused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'esMetricsExporter' defined in class path resource [com/alipay/sofa/lookout/gateway/metrics/exporter/es/spring/bean/config/EsExporterConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alipay.sofa.lookout.gateway.metrics.exporter.es.ESMetricExporter]: Factory method 'esMetricsExporter' threw exception; nested exception is java.lang.IllegalStateException: java.lang.IllegalStateException: this alias is conflicted with an index name:lookout-active-metrics
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:627)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:456)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1321)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1160)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.resolveBeanReference(ConfigurationClassEnhancer.java:394)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:366)
2019-10-11 17:24:4910.200.5.33419abfff	at com.alipay.sofa.lookout.gateway.metrics.exporter.es.spring.bean.config.EsExporterConfiguration$$EnhancerBySpringCGLIB$$d94b5932.esMetricsExporter(<generated>)
2019-10-11 17:24:4910.200.5.33419abfff	at com.alipay.sofa.lookout.gateway.metrics.exporter.es.spring.bean.config.EsExporterConfiguration.esMetricsExportChain(EsExporterConfiguration.java:54)
2019-10-11 17:24:4910.200.5.33419abfff	at com.alipay.sofa.lookout.gateway.metrics.exporter.es.spring.bean.config.EsExporterConfiguration$$EnhancerBySpringCGLIB$$d94b5932.CGLIB$esMetricsExportChain$1(<generated>)
2019-10-11 17:24:4910.200.5.33419abfff	at com.alipay.sofa.lookout.gateway.metrics.exporter.es.spring.bean.config.EsExporterConfiguration$$EnhancerBySpringCGLIB$$d94b5932$$FastClassBySpringCGLIB$$78efd180.invoke(<generated>)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
2019-10-11 17:24:4910.200.5.33419abfff	at com.alipay.sofa.lookout.gateway.metrics.exporter.es.spring.bean.config.EsExporterConfiguration$$EnhancerBySpringCGLIB$$d94b5932.esMetricsExportChain(<generated>)
2019-10-11 17:24:4910.200.5.33419abfff	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2019-10-11 17:24:4910.200.5.33419abfff	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2019-10-11 17:24:4910.200.5.33419abfff	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2019-10-11 17:24:4910.200.5.33419abfff	at java.lang.reflect.Method.invoke(Method.java:498)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
2019-10-11 17:24:4910.200.5.33419abfff	... 68 more
2019-10-11 17:24:4910.200.5.33419abfffCaused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alipay.sofa.lookout.gateway.metrics.exporter.es.ESMetricExporter]: Factory method 'esMetricsExporter' threw exception; nested exception is java.lang.IllegalStateException: java.lang.IllegalStateException: this alias is conflicted with an index name:lookout-active-metrics
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622)
2019-10-11 17:24:4910.200.5.33419abfff	... 91 more
2019-10-11 17:24:4910.200.5.33419abfffCaused by: java.lang.IllegalStateException: java.lang.IllegalStateException: this alias is conflicted with an index name:lookout-active-metrics
2019-10-11 17:24:4910.200.5.33419abfff	at com.alipay.sofa.lookout.server.common.es.operation.ESOperator.initializeDatabase(ESOperator.java:81)
2019-10-11 17:24:4910.200.5.33419abfff	at com.alipay.sofa.lookout.gateway.metrics.exporter.es.ESMetricExporter.<init>(ESMetricExporter.java:89)
2019-10-11 17:24:4910.200.5.33419abfff	at com.alipay.sofa.lookout.gateway.metrics.exporter.es.spring.bean.config.EsExporterConfiguration.esMetricsExporter(EsExporterConfiguration.java:49)
2019-10-11 17:24:4910.200.5.33419abfff	at com.alipay.sofa.lookout.gateway.metrics.exporter.es.spring.bean.config.EsExporterConfiguration$$EnhancerBySpringCGLIB$$d94b5932.CGLIB$esMetricsExporter$0(<generated>)
2019-10-11 17:24:4910.200.5.33419abfff	at com.alipay.sofa.lookout.gateway.metrics.exporter.es.spring.bean.config.EsExporterConfiguration$$EnhancerBySpringCGLIB$$d94b5932$$FastClassBySpringCGLIB$$78efd180.invoke(<generated>)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
2019-10-11 17:24:4910.200.5.33419abfff	at com.alipay.sofa.lookout.gateway.metrics.exporter.es.spring.bean.config.EsExporterConfiguration$$EnhancerBySpringCGLIB$$d94b5932.esMetricsExporter(<generated>)
2019-10-11 17:24:4910.200.5.33419abfff	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2019-10-11 17:24:4910.200.5.33419abfff	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2019-10-11 17:24:4910.200.5.33419abfff	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2019-10-11 17:24:4910.200.5.33419abfff	at java.lang.reflect.Method.invoke(Method.java:498)
2019-10-11 17:24:4910.200.5.33419abfff	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
2019-10-11 17:24:4910.200.5.33419abfff	... 92 more
2019-10-11 17:24:4910.200.5.33419abfffCaused by: java.lang.IllegalStateException: this alias is conflicted with an index name:lookout-active-metrics
2019-10-11 17:24:4910.200.5.33419abfff	at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
2019-10-11 17:24:4910.200.5.33419abfff	at com.alipay.sofa.lookout.server.common.es.operation.ESOperator.createIndex(ESOperator.java:90)
2019-10-11 17:24:4910.200.5.33419abfff	at com.alipay.sofa.lookout.server.common.es.operation.ESOperator.initializeDatabase(ESOperator.java:74)
2019-10-11 17:24:4910.200.5.33419abfff	... 104 more(url)

**Comment by luyiisme** [comment]
"java.lang.IllegalStateException: this alias is conflicted with an index name:lookout-active-metrics"。
你现在 ES 里面删除下 lookout-active-metrics index，然后再试下。
